language: python
os: linux
python:
   - 2.7.15
before_script: bash ./before_install.sh
script:
    - make travis_build
cache:
  directories:
    - $HOME/pebble-dev
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - python2.7-dev
    - python-pip
    - python-virtualenv
    - libssl-dev
    - libffi-dev
env:
  - PEBBLE_SDK=pebble-sdk-4.5-linux64 PEBBLE_PATH=cfg1/pebble-mss
